/**
 * Deterministic demo timeseries — pre-baked so server-render and client-hydrate match.
 * Replace with the live /risk/timeseries fetch in production.
 */
export const TIMESERIES: { score_date: string; composite_score: number }[] = [
  { score_date: "Jan 30", composite_score: 41.0 }, { score_date: "Jan 31", composite_score: 41.6 },
  { score_date: "Feb 1", composite_score: 42.1 }, { score_date: "Feb 2", composite_score: 41.8 },
  { score_date: "Feb 3", composite_score: 42.4 }, { score_date: "Feb 4", composite_score: 43.0 },
  { score_date: "Feb 5", composite_score: 42.7 }, { score_date: "Feb 6", composite_score: 43.4 },
  { score_date: "Feb 7", composite_score: 43.0 }, { score_date: "Feb 8", composite_score: 42.5 },
  { score_date: "Feb 9", composite_score: 42.2 }, { score_date: "Feb 10", composite_score: 42.8 },
  { score_date: "Feb 11", composite_score: 43.1 }, { score_date: "Feb 12", composite_score: 43.6 },
  { score_date: "Feb 13", composite_score: 44.0 }, { score_date: "Feb 14", composite_score: 43.4 },
  { score_date: "Feb 15", composite_score: 43.7 }, { score_date: "Feb 16", composite_score: 44.5 },
  { score_date: "Feb 17", composite_score: 44.9 }, { score_date: "Feb 18", composite_score: 45.2 },
  { score_date: "Feb 19", composite_score: 44.7 }, { score_date: "Feb 20", composite_score: 44.4 },
  { score_date: "Feb 21", composite_score: 44.8 }, { score_date: "Feb 22", composite_score: 45.3 },
  { score_date: "Feb 23", composite_score: 45.1 }, { score_date: "Feb 24", composite_score: 44.6 },
  { score_date: "Feb 25", composite_score: 44.2 }, { score_date: "Feb 26", composite_score: 44.9 },
  { score_date: "Feb 27", composite_score: 45.5 }, { score_date: "Feb 28", composite_score: 46.0 },
  { score_date: "Mar 1", composite_score: 46.4 }, { score_date: "Mar 2", composite_score: 45.9 },
  { score_date: "Mar 3", composite_score: 45.5 }, { score_date: "Mar 4", composite_score: 45.8 },
  { score_date: "Mar 5", composite_score: 46.2 }, { score_date: "Mar 6", composite_score: 46.7 },
  { score_date: "Mar 7", composite_score: 47.1 }, { score_date: "Mar 8", composite_score: 46.6 },
  { score_date: "Mar 9", composite_score: 46.2 }, { score_date: "Mar 10", composite_score: 46.5 },
  { score_date: "Mar 11", composite_score: 47.0 }, { score_date: "Mar 12", composite_score: 47.5 },
  { score_date: "Mar 13", composite_score: 48.1 }, { score_date: "Mar 14", composite_score: 47.7 },
  { score_date: "Mar 15", composite_score: 47.4 }, { score_date: "Mar 16", composite_score: 47.8 },
  { score_date: "Mar 17", composite_score: 48.2 }, { score_date: "Mar 18", composite_score: 48.7 },
  { score_date: "Mar 19", composite_score: 49.1 }, { score_date: "Mar 20", composite_score: 48.6 },
  { score_date: "Mar 21", composite_score: 48.2 }, { score_date: "Mar 22", composite_score: 47.8 },
  { score_date: "Mar 23", composite_score: 48.1 }, { score_date: "Mar 24", composite_score: 48.6 },
  { score_date: "Mar 25", composite_score: 49.0 }, { score_date: "Mar 26", composite_score: 49.5 },
  { score_date: "Mar 27", composite_score: 49.2 }, { score_date: "Mar 28", composite_score: 48.8 },
  { score_date: "Mar 29", composite_score: 48.4 }, { score_date: "Mar 30", composite_score: 48.9 },
  { score_date: "Mar 31", composite_score: 49.4 }, { score_date: "Apr 1", composite_score: 49.8 },
  { score_date: "Apr 2", composite_score: 49.4 }, { score_date: "Apr 3", composite_score: 49.0 },
  { score_date: "Apr 4", composite_score: 48.7 }, { score_date: "Apr 5", composite_score: 49.1 },
  { score_date: "Apr 6", composite_score: 49.5 }, { score_date: "Apr 7", composite_score: 49.0 },
  { score_date: "Apr 8", composite_score: 48.6 }, { score_date: "Apr 9", composite_score: 48.3 },
  { score_date: "Apr 10", composite_score: 48.7 }, { score_date: "Apr 11", composite_score: 49.2 },
  { score_date: "Apr 12", composite_score: 49.6 }, { score_date: "Apr 13", composite_score: 49.2 },
  { score_date: "Apr 14", composite_score: 48.9 }, { score_date: "Apr 15", composite_score: 48.5 },
  { score_date: "Apr 16", composite_score: 48.1 }, { score_date: "Apr 17", composite_score: 47.8 },
  { score_date: "Apr 18", composite_score: 47.5 }, { score_date: "Apr 19", composite_score: 47.9 },
  { score_date: "Apr 20", composite_score: 48.3 }, { score_date: "Apr 21", composite_score: 48.7 },
  { score_date: "Apr 22", composite_score: 48.4 }, { score_date: "Apr 23", composite_score: 48.0 },
  { score_date: "Apr 24", composite_score: 47.6 }, { score_date: "Apr 25", composite_score: 47.3 },
  { score_date: "Apr 26", composite_score: 47.0 }, { score_date: "Apr 27", composite_score: 47.4 },
  { score_date: "Apr 28", composite_score: 47.0 }, { score_date: "Apr 29", composite_score: 47.0 },
];
